export const CHANGE_SONG_LIST = 'CHANGE_SONG_LIST'
export const TOGGLE_SONG_PLAY = 'TOGGLE_SONG_PLAY'
export const NEXT_SONG = 'NEXT_SONG'
export const PRE_SONG = 'PRE_SONG'
export const CHANGE_SONG_INFO = 'CHANGE_SONG_INFO'
export const CHANGE_PLAYING_SONG = 'CHANGE_PLAYING_SONG'
export const TOGGLE_PLAYING_STATE = 'TOGGLE_PLAYING_STATE'
export const CHANGE_CURRNET_SONG_URL = 'CHANGE_CURRNET_SONG_URL'
export const CHANGE_CURRENT_SONG_TOTALTIME = 'CHANGE_CURRENT_SONG_TOTALTIME'
export const CHANGE_CUREENT_SONG_TIME = 'CHANGE_CUREENT_SONG_TIME'
export const CHANGE_CUREENT_SONG_USE_INDEX = 'CHANGE_CUREENT_SONG_USE_INDEX'
// 切换歌曲
export const switchSong = 'switchSong'
// 更新 mvlist
export const updateMvList = 'updateMvList'
export const changeMvPlayState = 'changeMvPlayState'
export const changeMvPlayIndex = 'changeMvPlayIndex'
